window.UNITED_EVENTS = [
  {date:'2026-09-05',title:'Season Opening Ride',location:'Al Qudra',cats:['Cycling','Community'],type:'united',past:true,description:'The ride that opened the UNITED 2026/27 season.'},
  {date:'2026-09-18',end:'2026-09-19',title:'Jebel Hafeet Weekend',location:'Jebel Hafeet, UAE',cats:['Cycling','Camp'],type:'united',description:'A UNITED mountain weekend.'},
  {date:'2026-09-26',title:'Movie Night in the Desert',location:'Dubai, UAE',cats:['Community'],type:'united',description:'A UNITED evening together in the desert.'},
  {date:'2026-09-27',title:'Running Technique Session',location:'Dubai, UAE',cats:['Running'],type:'united',description:'A dedicated UNITED running technique session.'},
  {date:'2026-10-03',title:'Coffee Ride — New City Routes',location:'Dubai, UAE',cats:['Cycling','Community'],type:'united',description:'A social ride exploring new city routes.'},
  {date:'2026-10-10',title:'Open Water Training',location:'Dubai, UAE',cats:['Swimming'],type:'united',description:'UNITED open-water training.'},
  {date:'2026-10-17',title:'Club Dinner',location:'Dubai, UAE',cats:['Community'],type:'united',description:'UNITED club dinner.'},
  {date:'2026-10-18',title:'Ajman Triathlon',location:'Ajman, UAE',cats:['Triathlon'],type:'race'},
  {date:'2026-10-18',title:'Aquaman Open Water Dubai',location:'Dubai, UAE',cats:['Swimming'],type:'race'},
  {date:'2026-10-24',title:'Karting Night',location:'Dubai, UAE',cats:['Community'],type:'united',description:'UNITED karting night.'},
  {date:'2026-10-24',title:'ARENA Open Water Swim',location:'UAE',cats:['Swimming'],type:'race'},
  {date:'2026-10-25',title:'GRIT+TONIC Mamzar Race 1',location:'Dubai, UAE',cats:['Triathlon'],type:'race'},
  {date:'2026-10-25',title:'Masfout MTB Challenge',location:'Masfout, UAE',cats:['Cycling'],type:'race'},
  {date:'2026-11-01',title:'Oceanic Khorfakkan Triathlon Race 1',location:'Khorfakkan, UAE',cats:['Triathlon'],type:'race'},
  {date:'2026-11-01',title:'OCEANMAN Prep — Open Water Training',location:'Dubai, UAE',cats:['Swimming'],type:'united',description:'Open-water preparation session.'},
  {date:'2026-11-07',title:'OCEANMAN Dubai',location:'Dubai, UAE',cats:['Swimming'],type:'race',team:true},
  {date:'2026-11-08',title:'T100 Transition Clinic',location:'Dubai, UAE',cats:['Triathlon'],type:'united',description:'UNITED transition practice ahead of Dubai T100.'},
  {date:'2026-11-13',end:'2026-11-15',title:'Dubai T100',location:'Al Mamzar, Dubai',cats:['Triathlon'],type:'race',team:true,distance:'T100 2 / 80 / 18 km · Olympic 1.5 / 40 / 10 km · Sprint 0.75 / 20 / 5 km',url:'https://t100triathlon.com/dubai/'},
  {date:'2026-11-13',end:'2026-11-22',title:'World Triathlon Multisport Championships Abu Dhabi',location:'Hudayriyat Island, Abu Dhabi',cats:['Triathlon'],type:'race'},
  {date:'2026-11-14',title:'Bike Abu Dhabi Gran Fondo',location:'Abu Dhabi, UAE',cats:['Cycling'],type:'race',team:true,distance:'150 km',url:'https://battistrada.com/en/cycling-calendar/edition/bike-abu-dhabi-gran-fondo-2026/54934/'},
  {date:'2026-11-15',title:'UNITED Yacht Party',location:'Dubai, UAE',cats:['Community'],type:'united',description:'UNITED yacht party after the T100 weekend.'},
  {date:'2026-11-21',title:'NBF Fujairah Trail Run',location:'Fujairah, UAE',cats:['Running'],type:'race'},
  {date:'2026-11-22',title:'Ajman Cycling Race',location:'Ajman, UAE',cats:['Cycling'],type:'race'},
  {date:'2026-12-02',end:'2026-12-03',title:'Fujairah Family Camp',location:'Fujairah, UAE',cats:['Camp','Community'],type:'united',description:'A two-day UNITED family camp in Fujairah.'},
  {date:'2026-12-05',title:'IRONMAN Oman',location:'Muscat, Oman',cats:['Triathlon'],type:'race',team:true,url:'https://www.ironman.com/races/im-oman'},
  {date:'2026-12-12',title:'ADNOC Abu Dhabi Marathon',location:'Abu Dhabi, UAE',cats:['Running'],type:'race',team:true},
  {date:'2026-12-12',end:'2026-12-13',title:'Jebel Jais Weekend',location:'Jebel Jais, UAE',cats:['Cycling','Camp'],type:'united'},
  {date:'2026-12-13',title:'Fujairah International Triathlon',location:'Fujairah, UAE',cats:['Triathlon'],type:'race'},
  {date:'2026-12-19',title:'UNITED End of Year Dinner',location:'Dubai, UAE',cats:['Community'],type:'united',description:'Our year-end dinner and season recap.'},
  {date:'2026-12-27',title:'Christmas Ride + Dinner',location:'Dubai, UAE',cats:['Cycling','Community'],type:'united',description:'An evening Christmas ride followed by dinner.'},
  {date:'2027-01-16',title:'RAK TRI 113 / 76',location:'Ras Al Khaimah, UAE',cats:['Triathlon'],type:'race'},
  {date:'2027-01-17',title:'Dubai Marathon',location:'Dubai, UAE',cats:['Running'],type:'race',team:true,url:'https://dubaimarathon.org/'},
  {date:'2027-01-24',title:'Burj2Burj',location:'Dubai, UAE',cats:['Running'],type:'race',team:true},
  {date:'2027-01-29',end:'2027-01-31',title:'Challenge Sir Bani Yas',location:'Sir Bani Yas Island, Abu Dhabi',cats:['Triathlon','Camp'],type:'race',team:true,major:true,description:'One of the key UNITED races of the season. Race weekend 30–31 January.',offer:'25% launch offer',url:'https://endurancecui.active.com/event-reg/select-race?e=96445611'},
  {date:'2027-01-31',title:'Masfout Trail Run',location:'Masfout, UAE',cats:['Running'],type:'race'},
  {date:'2027-02-06',title:'IRONMAN 70.3 Muscat',location:'Muscat, Oman',cats:['Triathlon'],type:'race',team:true},
  {date:'2027-02-07',title:'Spinneys Dubai 92 Cycle Challenge',location:'Dubai, UAE',cats:['Cycling'],type:'race',team:true,major:true,distance:'94.1 km'},
  {date:'2027-03-10',end:'2027-03-15',title:'UNITED South Africa Cycling Camp',location:'South Africa',cats:['Cycling','Camp'],type:'united',major:true,description:'UNITED cycling camp in South Africa.'},
  {date:'2027-03-13',title:'GRIT+TONIC Triathlon Al Mamzar',location:'Dubai, UAE',cats:['Triathlon'],type:'race'},
  {date:'2027-03-14',title:'Cape Town Cycle Tour',location:'Cape Town, South Africa',cats:['Cycling'],type:'race',team:true,distance:'109 km',url:'https://www.capetowncycletour.com/'},
  {date:'2027-03-14',title:'Oceanic Khorfakkan Race 2',location:'Khorfakkan, UAE',cats:['Triathlon'],type:'race'},
  {date:'2027-03-20',title:'ARENA Open Water Swim',location:'UAE',cats:['Swimming'],type:'race'},
  {month:'2027-04',title:'UNITED Maldives Swim Camp + OCEANMAN',location:'Maldives',cats:['Swimming','Camp'],type:'united',major:true,tbc:true,description:'UNITED swim camp in the Maldives. April date to be announced.'},
  {month:'2027-05',title:'IRONMAN 70.3 Shanghai Chongming',location:'Shanghai, China',cats:['Triathlon'],type:'race',tbc:true}
];